### ISSUE TITLE
방 상태 및 방 정보 관리하기 (전역상태)

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#20]
## Describe
방 상태 및 방 정보 관리

## Tasks
- [ ] 방 상태 변화 감지하기
- [ ] 변화할 때 방 정보 가져오기

- [x] 전역상태 방 정보 저장하기
- [x] 1,2... 일차 관리하기
