### ISSUE TITLE
게임 입장 수정

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#24]
## Describe
기획 추가, api 수정, 코드 구조 수정에 따라 게임 입장 수정

## Tasks
- [x] api http 미리 정의하는 방식으로 수정
- [x] 코드가 없을 경우 토스트 띄워주기
- [x] 이름중복일 경우 토스트 띄워주기
- [x] 게임입장 후 auth 저장
- [x] 방장만 게임시작 버튼 보이게
- [x] 초대하기 코드 받아오고, 공유링크 생성하기

## More
react-hot-toast 라이브러리 사용중입니다.
토스트는 3초로 통일하면 좋을 거 같아요.
