### ISSUE TITLE
낮 - 방 정보처리 및 분기처리

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#26]
## Describe
낮 방 정보 가져오기
정보에 따른 각 처리

## Tasks
- [x] 시간 처리
- 1일차 2일차에 따라 다르게 처리
- [x] 1일차: 본인 직업 공지
- [x] 2일차: 죽은사람 찾아서 공지

- [x] 본인이 죽었는지 살았는지에 따라 다르게 처리(각각 투표하기, 직업보기 보이게, 채팅 input)

- [x] 투표시간이 되면 (모두 투표했는지, 시간이 다된건지 구분)
- [x] 투표 결과 공지
