### ISSUE TITLE
낮 채팅방과 공지로 전환될 때 덜컹더리는 느낌 수정하기

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#35]
## Describe
현재 '낮이 되었습니다' 에서 다음 화면으로 이동될 때 덜컹거리는 현상이 있다.
모든 dom이 그려졌을 때 보이게 해서 자연스럽게 보이도록 해야할 것 같다.

## Tasks
- [ ] 로딩되고 화면이 나타나도록하기
- [ ] 이름입력할 때도 마찬가지
- [ ] 초대코드입력할 때도
- [ ] 방 만들기 할 때도 img가 불러와졌을 때 보이도록 해야할 것 같다

**Comment by cheonjiyun** [comment]
status에 따라 바꾸기로한뒤 별로 느끼지 못했다.
