### ISSUE TITLE
[hotfix] QA를 위한 핫픽스

### ISSUE THREAD

**Issue by kpeel5839** [mafia-together/frontend#62]
## Describe

예외가 발생하지 않게 하기 위한 핫픽스입니다.

## Tasks
- [ ] job, info를 recoil로 변경
- [ ] status 도 폴링 주기를 0.5초
- [ ] 채팅 ref 설정
