### ISSUE TITLE
대기방 구현

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#8]
## Describe
요약

## Tasks
- [x] 모자른 참가인원은 빈 이름으로
- [x] Polling방식으로 참가목록 API 계속 불러오기 -> 숫자, 플레이어 업데이트
- [x] 모든 인원이 찼을 때만 게임시작 가능
